#!/bin/env bash

# Install FD
sudo apt install fd-find
sudo ln -s $(which fdfind) /usr/bin/fd

# Install fonts
./parts/fonts-install

# Install Oh-My-ZSH
./parts/zsh-install.sh

# Languages
## NodeJS
### NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

## Rust
### Cargo and Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

### Cargo-edit
/bin/cargo install cargo-edit

