#!/bin/env bash

# Shell
## ZSH
if command -v apt &> /dev/null
then
	sudo apt install zsh
fi

## Oh-My-ZSH
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Languages
## NodeJS
### NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash

## Rust
### Cargo and Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

### Cargo-edit
/bin/cargo install cargo-edit

