theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.lsp]
display-inlay-hints = true
